import { describe, expect, it } from "vitest";
import { CodePreparation } from "../../src/code-sandbox/CodePreparation.ts";

const wrapCallableBody = (source: string): string =>
  [
    "const __fn = (",
    source,
    ");",
    'if (typeof __fn !== "function") throw new Error("Code must evaluate to a function");',
    "return await __fn();",
  ].join("\n");

describe("CodePreparation.recoverExecutionBody", () => {
  it("returns an empty body for an empty string", () => {
    expect(CodePreparation.recoverExecutionBody("")).toBe("");
  });

  it("returns an empty body for whitespace-only", () => {
    expect(CodePreparation.recoverExecutionBody("   \n  ")).toBe("");
  });

  it("wraps async arrows so standalone function submissions are invoked", () => {
    expect(CodePreparation.recoverExecutionBody("async () => { return 1; }")).toBe(
      wrapCallableBody("async () => { return 1; }"),
    );
  });

  it("strips export default from async arrows", () => {
    expect(CodePreparation.recoverExecutionBody("export default async () => 42")).toBe(
      wrapCallableBody("async () => 42"),
    );
  });

  it("accepts a parenthesized async arrow from a fenced block", () => {
    expect(CodePreparation.recoverExecutionBody("```ts\n(async () => 42)\n```")).toBe(
      wrapCallableBody("(async () => 42)"),
    );
  });

  it("strips export default from a parenthesized async arrow", () => {
    expect(CodePreparation.recoverExecutionBody("export default (async () => 42)")).toBe(
      wrapCallableBody("async () => 42"),
    );
  });

  it("wraps a named function declaration and calls it", () => {
    expect(CodePreparation.recoverExecutionBody("function hello() { return 42; }")).toBe(
      "function hello() { return 42; }\nreturn await hello();",
    );
  });

  it("wraps a sync anonymous function declaration from a fence", () => {
    expect(
      CodePreparation.recoverExecutionBody("```javascript\nfunction () { return 42; }\n```"),
    ).toBe("return await (function () { return 42; })();");
  });

  it("wraps an exported default named async function declaration", () => {
    expect(
      CodePreparation.recoverExecutionBody("export default async function run() { return 'ok'; }"),
    ).toBe("async function run() { return 'ok'; }\nreturn await run();");
  });

  it("wraps an exported default anonymous async function declaration", () => {
    expect(
      CodePreparation.recoverExecutionBody("export default async function () { return 'ok'; }"),
    ).toBe("return await (async function () { return 'ok'; })();");
  });

  it("ignores leading comments before an async arrow", () => {
    const code = [
      "// calling tools.search with the narrowed namespace",
      'async () => await tools.search({ query: "list contacts", namespace: "crm", limit: 5 })',
    ].join("\n");

    expect(CodePreparation.recoverExecutionBody(code)).toBe(wrapCallableBody(code));
  });

  it("handles block comments before export default", () => {
    const code = ["/* generated by the model */", "export default async () => 42"].join("\n");

    expect(CodePreparation.recoverExecutionBody(code)).toBe(wrapCallableBody("async () => 42"));
  });

  it("handles uppercase fence labels", () => {
    expect(CodePreparation.recoverExecutionBody("```TypeScript\nasync () => 42\n```")).toBe(
      wrapCallableBody("async () => 42"),
    );
  });

  it("extracts fenced code from surrounding prose", () => {
    const code = [
      "Use this exact snippet.",
      "",
      "```ts",
      'return await tools.search({ query: "github issues", limit: 5 });',
      "```",
      "",
      "That should do it.",
    ].join("\n");

    expect(CodePreparation.recoverExecutionBody(code)).toBe(
      'return await tools.search({ query: "github issues", limit: 5 });',
    );
  });

  it("keeps a multi-statement body that already returns", () => {
    const code = 'const query = "github issues";\nreturn await tools.search({ query, limit: 5 });';

    expect(CodePreparation.recoverExecutionBody(code)).toBe(code);
  });

  it("keeps a complex multi-step function body intact", () => {
    const code = [
      'const query = "recent pull requests";',
      "const limit = 5;",
      "",
      "function pickTop(matches) {",
      "  return matches.slice(0, 3).map((match) => match.path);",
      "}",
      "",
      "try {",
      "  const matches = await tools.search({ query, limit });",
      "  const top = pickTop(matches);",
      '  console.log("top results", top);',
      "  return { count: matches.length, top };",
      "} catch (error) {",
      "  return {",
      "    error: error instanceof Error ? error.message : String(error),",
      "    query,",
      "  };",
      "}",
    ].join("\n");

    expect(CodePreparation.recoverExecutionBody(code)).toBe(code);
  });

  it("extracts a complex fenced function body from surrounding prose", () => {
    const body = [
      "const owner = 'openai';",
      "const repo = 'executor';",
      "",
      "const issues = await tools.github.listRepositoryIssues({ owner, repo });",
      "const titles = issues",
      "  .slice(0, 5)",
      "  .map((issue) => issue.title)",
      "  .filter(Boolean);",
      "",
      "return {",
      "  owner,",
      "  repo,",
      "  titles,",
      "};",
    ].join("\n");

    const code = [
      "Run this:",
      "",
      "```ts",
      body,
      "```",
      "",
      "It should return the top issue titles.",
    ].join("\n");

    expect(CodePreparation.recoverExecutionBody(code)).toBe(body);
  });

  it("wraps a complex async arrow body for invocation", () => {
    const code = [
      "async () => {",
      '  const query = "list contacts";',
      "  const results = await tools.search({",
      "    query,",
      '    namespace: "crm",',
      "    limit: 5,",
      "  });",
      "",
      "  return results.map((result) => ({",
      "    path: result.path,",
      "    score: result.score ?? null,",
      "  }));",
      "}",
    ].join("\n");

    expect(CodePreparation.recoverExecutionBody(code)).toBe(wrapCallableBody(code));
  });
});

describe("CodePreparation.stripTypeScript", () => {
  it("removes variable type annotations", () => {
    const out = CodePreparation.stripTypeScript('const x: string = "hello"; return x;');

    expect(out).not.toContain(": string");
    expect(out).toContain("const x");
    expect(out).toContain('"hello"');
  });

  it("removes function param and return type annotations", () => {
    const out = CodePreparation.stripTypeScript(
      "function f(x: number): number { return x + 1; } return f(5);",
    );

    expect(out).not.toContain(": number");
    expect(() => new Function(out)).not.toThrow();
  });

  it("removes interfaces, type aliases, casts, and call generics", () => {
    const out = CodePreparation.stripTypeScript(
      [
        "interface User { name: string; }",
        "type Id = string;",
        "const user = { name: 'Ada' } as User;",
        "const ids = Array.from<Id>([]);",
        "return { user, ids };",
      ].join("\n"),
    );

    expect(out).not.toContain("interface User");
    expect(out).not.toContain("type Id");
    expect(out).not.toContain(" as User");
    expect(out).not.toContain("<Id>");
    expect(() => new Function(out)).not.toThrow();
  });

  it("preserves plain JavaScript semantics", () => {
    const out = CodePreparation.stripTypeScript("const x = 5; return x * 2;");

    expect(new Function(out)()).toBe(10);
  });

  it("strips complex async function expression annotations", () => {
    const code = `
      const fetchResources = async (sourceId: string): Promise<Array<{ id: string }>> => {
        const result = await tools.executor.sources.list();
        return result.items;
      };
      return fetchResources('example-source');
    `;
    const out = CodePreparation.stripTypeScript(code);

    expect(out).not.toContain(": string");
    expect(out).not.toContain("Promise<");
    expect(() => new Function(out)).not.toThrow();
  });

  it("throws for invalid syntax before code reaches workerd", () => {
    expect(() => CodePreparation.stripTypeScript("const = 5;")).toThrow();
  });

  it("leaves smart quote syntax for the worker compile boundary to reject", () => {
    const out = CodePreparation.stripTypeScript("return “hello”;");

    expect(out).toContain("“hello”");
  });
});

describe("CodePreparation.prepareUserCode", () => {
  it("recovers then strips TypeScript", () => {
    const out = CodePreparation.prepareUserCode("```ts\nasync (): Promise<number> => 42\n```");

    expect(out).toContain("const __fn = (");
    expect(out).toContain("async () => 42");
    expect(out).not.toContain(": Promise<number>");
  });
});
