import { pgTable, text } from "drizzle-orm/pg-core";

// Better Auth-owned tables (user/session/account/verification), generated by
// `bun run auth:schema`. Better Auth manages these rows directly — there is no
// external IdP to sync from.
export { account, session, user, verification } from "./schema/auth.ts";

export const records = pgTable("records", {
  id: text("id").primaryKey(),
  createdAt: text("created_at").notNull(),
});

export * as schema from "./schema.ts";
